---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plotly-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: plotly-app
  template:
    metadata:
      labels:
        app: plotly-app
    spec:
      containers:
      - name: plotly-app
        image: 372203683100.dkr.ecr.eu-west-2.amazonaws.com/dash-test:latest
        ports:
        - containerPort: 8050
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: plotly-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8050
  selector:
    app: plotly-app
